language: smalltalk
sudo: false

smalltalk:
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
  - GemStone-2.4.8
  - GemStone-3.1.0.6
  - GemStone-3.2.15
  - GemStone-3.3.1

smalltalk_config: .smalltalk.ston

os: linux

cache:
  directories:
    - $SMALLTALK_CI_CACHE

